### ISSUE TITLE
Where can I obtain three constant masks？

### ISSUE THREAD

**Issue by morestart** [198808xc/Pangu-Weather#28]
(the topography mask, land–sea mask and soil-type mask)

**Comment by 198808xc** [comment]
Hi,

These masks were produced from the downloaded ERA5 data. For your convenience, we have attached the files in the updated repository (see the new folder `constant_masks`).

**Comment by 0rhisia0** [comment]
Hi. This confuses me. In this reply https://github.com/198808xc/Pangu-Weather/issues/4#issuecomment-1547141059 the mask is referred to as a learnable parameter, i.e that the masks are contained within the model and that to reproduce results I do not need to add anything to the raw ERA5 data (since the mask is contained as a parameter in the model). Why are you providing the masks now in that case?

**Comment by 198808xc** [comment]
We used these constant masks, but added some learnable weights on it, which was actually caused by accident. In summary,

1. We did establish our system upon these constant masks.
2. For the exact details, please refer to the onnx file.
3. Using these constant masks without learnable weights will not cause accuracy drop (if one re-trains the system).

**Comment by 654493176** [comment]
> We used these constant masks, but added some learnable weights on it, which was actually caused by accident. In summary,
> 
> 1. We did establish our system upon these constant masks.
> 2. For the exact details, please refer to the onnx file.
> 3. Using these constant masks without learnable weights will not cause accuracy drop (if one re-trains the system).

您好，感谢您伟大的工作。我在查看您发布的常量掩膜时，发现在soil_type中没有第6类，但根据era5的文档，这个数据有7类，您是否有对常量数据做什么处理？期待您的回复。
![9eb25320cd15a1836f1a182c0f40ab2](https://github.com/198808xc/Pangu-Weather/assets/40239724/a3fe9cb2-f9ed-49bf-bf6f-19ed5e345808)
